src/Rimed/BlogBundle/Form/PostType.php
<?php

namespace Rimed\BlogBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

class PostType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('enabled', 'checkbox', array('label' => 'Habilitado:'));
        $builder->add('title', 'text', array('label' => 'Título:'));
        //TODO:
        //$builder->add('categories');
        $builder->add('abstract', 'textarea', array('label' => 'Resumen:'));
        $builder->add('content', 'textarea', array('label' => 'Contenido:'));
        //TODO:
        //$builder->add('tags');
        $builder->add('publicationDateStart', 'datetime', array('label' => 'Fecha de inicio de publicación:'));
        $builder->add('commentsEnabled', 'checkbox', array('label' => 'Comentarios habilitados:'));
        $builder->add('commentsCloseAt', 'datetime', array('label' => 'Fecha de cierre de los comentarios:'));
        $builder->add('commentsDefaultStatus', 'choice', array(
            'label' => 'Estado por defecto para los comentarios',
            'choices' => array(0 => 'Válido', 1 => 'Inválido', 2 => 'Moderado')
        ));
        
        /*
        $builder->add('ponente', 'entity', array(
            'class'         => 'Rimed\\BlogBundle\\Entity\\BasePost',
            'query_builder' => function ($repositorio) {
                return $repositorio->createQueryBuilder('p')->orderBy('p.nombre', 'ASC');
            },
        ));
         */
    }
    
    public function getDefaultOptions(array $options)
    {
        return array(
            'data_class' => 'Rimed\\BlogBundle\\Entity\\BasePost',
        );
    }

    public function getName() 
    {
        return "Post";
    }
}

src/Rimed/BlogBundle/Resources/views/Admin/Comment/list.html.twig
{% extends "RimedBlogBundle::layout.html.twig" %}

{% block title %}Listado de comentarios{% endblock %}

{% block content %}

<a href="{{ path('blog_admin_index') }}">Regresar a la administración</a>

<h3>Filtros</h3>

<a href="#">Todos (X)</a>
<a href="#">Pendientes (X)</a>
<a href="#">Aprobados (X)</a>
<a href="#">Spam (X)</a>
<a href="#">Papelera (X)</a>

<table border="1">
    <thead>
        <tr>
            <th><input type="checkbox"></th>
            <th>Número</th>
            <th>Autor</th>
            <th>Estado</th>
            <th>Comentario</th>
            <th>Publicación</th>
        </tr>
    </thead>

    <tbody>
        {% for comment in comments %}
            <tr>
                <td><input type="checkbox"></td>
                <td align="center">{{ loop.index }}</td>
                <td><a href="{{ path('blog_admin_comment_edit', {'id': comment.id}) }}">{{ comment.name }}</a></td>
                <td>{{ comment.status }}</td>
                <td>{{ comment.message }}</td>
                <td>{{ comment.post.title }}</td>
            </tr>
        {% else %}
            <br>No existe ningún comentario!!!<br><br>
        {% endfor %}
    </tbody>
</table>

<a href="#">Eliminar seleccionadas</a>

{% endblock %}